#Name: William Tan
#Email: willtan510@gmail.com 
#ID: 104770108

files= lab1a.c Makefile README

all:
	@gcc -o lab1a -g ./lab1a.c -Wall -Wextra

dist:
	@tar -czf lab1a-104770108.tar.gz $(files)

clean:
	rm -f lab1a-104770108.tar.gz lab1a
