#NAME: Jonathan Chon, William Tan
#EMAIL: jonchon@gmail.com, willtan510@gmail.com


default:
	@cp lab3b.py lab3b
	@chmod 777 lab3b lab3b.py

clean:
	@rm -f *.tar.gz lab3b

dist: clean default
	@tar -czf lab3b-104770108.tar.gz lab3b.py Makefile README
